weather_observations_and_forecasting:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('MAIN_DB', 'weatherdb') }}"
      schema: "{{ env_var('STAGING_SCHEMA', 'staging') }}"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
